name: Deploy

on:
  push:
    branches:
      - main
env:
  VITE_SERVICE_ID: ${{ secrets.VITE_SERVICE_ID }}
  VITE_TEMPLATE_ID: ${{ secrets.VITE_TEMPLATE_ID }}
  VITE_USER_ID: ${{ secrets.VITE_USER_ID }}
  
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 22

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Build project
        run: npm run build

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v2
        with:
          name: production-files
          path: ./dist

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 22

      - name: Setup json-server
        run: npm i json-server -g

      - name: Run json-server
        run: json-server --watch ./dist/DB.json --port 3001

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: production-files
          path: ./dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist